apiVersion: v1
kind: Service
metadata:
  name: kubtest
  namespace: demospace
  labels:
    app: kubtest
spec:
  ports:
  - port: 80
    name: demostateful
  clusterIP: None
  selector:
    app: kubtest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demostateful
  namespace: demospace
spec:
  serviceName: "kubtest"
  replicas: 2
  selector:
    matchLabels:
      app: kubtest
  template:
    metadata:
      labels:
        app: kubtest
    spec:
      containers:
      - name: kubtest
        image: localhost:5000/kubtesting:106
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
